#!/bin/bash

sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i 's/80 default_server;/80;/g' /etc/nginx/sites-available/default
sudo /etc/init.d/nginx restart
