#!/usr/bin/env bash
# Display "Best School" 10 times. And if the counter is 9, display "Hi" as well

count=1

while [ $count -le 10 ]
do
    echo "Best School"
    if [ $count -eq 9 ]
    then
        echo "Hi"
    fi
    ((count++))
done