#!/usr/bin/env bash
# Loop through the numbers 1 to 10 and print "Best School" for each iteration

count=1

while [ $count -le 10 ]
do
    if [ $count -eq 4 ]
    then
        echo "bad luck"
    elif [ $count -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((count++))
done